### ISSUE TITLE
Adicionar imagens a perguntas de um jogo

### ISSUE THREAD

**Issue by guilhermeV20** [lamiautfpr/ICT01-2019-backend-E-Battle#68]
Para adicionar uma imagem, será necessário passar o base64 da mesma no json da pergunta, a imagem será então salva no S3 e na requisição de games será retornado o link para acesso da imagem, este sendo um link apontando para o CloudFront que servirá os arquivos estáticos da plataforma.

Caminho das imagens no S3:  `games/questions/YYYY/MM/dd/UserId-HHmmSS-index.png`
Exemplo: `games/questions/2023/04/01/2-145558-1.png`

```javascript
const buf = Buffer.from(question.image.replace(/^data:image\/\w+;base64,/, ""),'base64');
await s3.send(new PutObjectCommand({
    Bucket: 'ebattle-api-static-'+process.env.ENVIRONMENT,
    Key: 'games/questions/YYYY/MM/dd/'+user+"-"+"HHmmSS"+"-"+index+'.png',
    Body: buf,
    ContentType: 'image/png',
}));
```

Após salvar as imagens adicione a pergunta o caminho do S3 usado para salvar a image.

Para melhorar a performance quando houveram múltiplas imagens em uma requisição, encapsule as requisições de upload em um `Promise.all()`, fazendo o upload de todas as imagens de uma única vez.
Outro ponto a se atentar é limitar o tamanho máximo das imagens, podemos começar com 20MB e alterar quando necessário.

Para a leitura das imagens e duplicação de games outras issues serão criadas.

**Comment by ErikHenrique09** [comment]
Push das alterações do yaml e do endpoint games para receber imagens
